const Map<String, String> classInfo = {
  'banten_dogdoglojor':
      'Dogdog Lojor\n\nThe name "dogdog" comes from the sound produced by this percussion instrument. The word "lojor" (Sundanese) means long, derived from the size of the instrument.\n\n This "dogdog" musical instrument is made of wood in the shape of an elongated cylinder with a hollow center. The two ends of the hollow are not the same; one end has a diameter of approximately 15 cm, while the other end has a diameter of approximately 13 cm. Meanwhile, its length is approximately 90 cm, my friend. The larger circular end is usually covered with dried goat skin. Then tied with bamboo that is paseuk or wedged with the intention of tuning the sound produced.\n\n below is a link to purchase and how to play the musical instrument \n*disclaimer admin is not responsible for the link below\n\npurchase link = ""\n\nvideo link = "https://www.youtube.com/watch?v=sCsPgA4M8vM"',
  'jakarta_tehyan':
      'Tehyan \n\nTehyan comes from the capital city of Jakarta which has a type of chordophone sound that is used by rubbing the strings or strings, almost the same as playing the violin.\n\n below is a link to purchase and how to play the musical instrument \n*disclaimer admin is not responsible for the link below\n\npurchase link = "https://www.tokopedia.com/rori160614/ready-tehyan-bukan-cort-fender-ibanez-gibson-godin-takamine?extParam=ivf%3Dfalse%26keyword%3Dtehyan%26search_id%3D202506240309434734BA6F3DE83D2648ZZ%26src%3Dsearch"\n\n video link = "https://www.youtube.com/watch?v=yUyYvlnVfwc"',
  'jawabarat_angklung':
      'Angklung\n\n Angklung is a traditional musical instrument originating from West Java that is played by shaking it. The types of bamboo commonly used to make angklung are awi wulung (black bamboo) and awi temen (white bamboo). Each tone or tone produced is produced from the sound of bamboo tubes in the form of wilahan (blades) for each bamboo segment starting from large sizes.\n\nThe famous angklung figure in Sunda is Udjo Ngalagena, the founder of Saung Angklung Udjo in Bandung who has developed angklung playing techniques based on salendro, pelog and madenda tunings since 1966.\n\n below is a link to buy and how to play the musical instrument \n*disclaimer admin is not responsible for the link below\n\npurchase link = "https://www.tokopedia.com/craftnusantara/angklung-satuan-bambu-hitam-3-tabung-tali-rotan-hitam-nada-do-tinggi?extParam=ivf%3Dfalse%26keyword%3Dangklung%26search_id%3D20250624034547320722549D17513B4TPQ%26src%3Dsearch"\n\n video link = "https://www.youtube.com/watch?v=COqgqRlrrWY"',
  'jawabarat_calung':
      'Calung \n\nCalung is a Sundanese musical instrument that is almost the same as the angklung. The way to play the calung is by hitting the bars of the segments arranged according to the pitch or pentatonic scale (da-mi-na-ti-la).\n\n One of the maestros of the Sundanese calung is Mbah Darso (Alm) who popularized the angklung with his works. So this traditional Sundanese musical instrument is better known in the community.\n\n below is a link to purchase and how to play the instrument \n*disclaimer admin is not responsible for the link below\n\npurchase link = "https://www.tokopedia.com/poppymar/dijual-calung-sunda-satu-set-4-sisir-diskon?extParam=ivf%3Dfalse%26keyword%3Dcalung%26search_id%3D20250624035347DB8E1AF0CB3ACA179HHZ%26src%3Dsearch"\n\n video link = "https://www.youtube.com/watch?v=WKWNb4FM_h8"',
  'jawabarat_celempung':
      'Celempung\n\n Celempung utilizes the resonance waves that exist in the bamboo stem segments. This musical instrument itself is made of bamboo. The celempung beater is made of wood or bamboo with a cloth or other thin object attached to the end to produce a loud sound.\n\n This instrument is played by hitting it or by adjusting the size of the air coming out of the celempung body with your hands.\n\n Below is a link to purchase and how to play the instrument \n*disclaimer admin is not responsible for the link below\n\npurchase link = "https://www.tokopedia.com/giripurwaseni/celempung-bambu-sunda-1729578148059777661?extParam=ivf%3Dfalse%26keyword%3Dcelempung%26search_id%3D2025062404031234ED066DF378EF0D5DJP%26src%3Dsearch"\n\n video link = "https://www.youtube.com/watch?v=RUXKTjjk-QM"',
  'jawabarat_gong':
      'Gong\n\nGongs are a typical West Javanese percussion instrument. They can be found in gamelan ensembles and are large, round in shape.\n\n Gongs are a popular percussion instrument in Southeast and East Asia. Gongs are now rare. Gongs that have been forged cannot be tuned. The gongs tone is only determined after rinsing and cleaning. If the tone is still not right, the gong is scraped to remove the bronze layer.yes, it becomes thinner.\n\n below is a link to purchase and how to play the musical instrument \n*disclaimer admin is not responsible for the link below\n\npurchase link = "https://www.tokopedia.com/garasi08561303623sasi/gong-peresmian-diameter-80cm-besi-plat-sewa?extParam=ivf%3Dfalse%26keyword%3Dgong+besi%26search_id%3D20250624040518B3967A0E938DC211850O%26src%3Dsearch"\n\n video link = "https://www.youtube.com/watch?v=tkTXxUR0k_4"',
  'jawabarat_karinding':
      'Karinding\n\n This musical instrument has become popular among young Sundanese since 2008, after this instrument was introduced by UjungBerung rebels metal kids. Especially with their Karinding attack music group. Sundanese musical instrument made from the trunk of the kawung (sugar palm) tree or bamboo and played by striking the fingertips and holding it in the mouth.\n\n Karinding has been used in the Sunda region since the 15th century, especially in the Tasikmalaya area. This musical instrument can be played solo or in groups (2-5 people). Karinding is included in the family of mouth harp musical instruments and is still the same type as the génggong musical instrument from Bali and kuriding from South Kalimantan. Although it has not been scientifically tested, the Sundanese people of old believe that the sound produced by this traditional Sundanese musical instrument can repel pests in the rice fields, because it produces low-decible or ultrasonic sounds.\n\n below is a link to purchase and how to play the instrument \n*disclaimer admin is not responsible for the link below\n\npurchase link = "https://www.tokopedia.com/dansdoang/karinding-bambu?extParam=ivf%3Dfalse%26keyword%3Dkarinding%26search_id%3D20250624040555577BCC914F9E55319PXX%26src%3Dsearch"\n\n video link = "https://www.tiktok.com/@yogi_karinding_real/video/7437466208435326263"',
  'jawabarat_kecapi':
      'Kecapi\n\n This traditional Sundanese musical instrument is played by plucking and is usually accompanied by the strains of the Sundanese flute to accompany Sundanese kawih or Cianjuran songs.\n\nThe kecapi is usually made of cananga wood while the strings of the kecapi are made of steel wire, in ancient times the strings of the kecapi were made of a mixture of gold and copper metal so that the sound produced was louder.\n\nThe strains of the kecapi flute can make people, especially Sundanese people who are away from home, divert their imagination to their hometown. With rice fields covered with green trees, mountains and people doing activities around it.\n\n below is a link to buy and how to play the musical instrument \n*disclaimer admin is not responsible for the link below\n\npurchase link = "https://www.tokopedia.com/ayusatriani/terlaris-guzheng-kecapi-alat-musik-tradisional-cina-termurah-1731170720675759114?extParam=ivf%3Dfalse%26keyword%3Dalat+musik+kecapi%26search_id%3D202506240407433FE94A002317B5203NM6%26src%3Dsearch"\n\n video link = "https://www.youtube.com/watch?v=HxWLZxlRw_o"',
  'jawabarat_rebab':
      'Rebab\n\n The material used to make the rebab is copper, but in its development, the elongated part of the rebab is made from jackfruit wood. While the body is made of hollow wood covered with skin, intestines, or dried cow urine.\n\nThis musical instrument is played similarly to a violin, namely by bowing. In addition, the rebab has two to three strings made of metal.\n\nThe rebab is included in the series of gamelah instruments that are usually used to accompany wayang celempungan, kliningan, or Cianjuran song performances. The rebab serves as a guide for songs and entered Indonesia through Islamic trade routes.\n\n Below is a link to purchase and learn how to play the instrument. \n*Disclaimer: The admin is not responsible for the link below.\n\npurchase link = "https://www.tokopedia.com/maliko-1/rebab-gamelan-jawa-kayu-sonokeling-murah?extParam=ivf%3Dfalse%26keyword%3Drebab%26search_id%3D202506240408173AD7C2EBB96FCB03AKAS%26src%3Dsearch"\n\nvideo link = "https://www.youtube.com/watch?v=FgRFM4g6mBI"',
  'jawabarat_suling':
      'Suling \n\nThe flute is a type of Sundanese gamelan instrument that is played by blowing. Sundanese flutes have four or six holes and have a distinctive sound. \n\n Sundanese flutes are made from Tamiang bamboo (lemang bamboo), which is thin and small in diameter. The size of the flute determines the high and low sound, for tembang songs, the flute used is around 60-65 cm (the sound is lower), this size is longer than the flute used for wedding accompaniment or degung with a length of 50-59 cm.\n\n below is a link to buy and how to play the musical instrument \n*disclaimer admin is not responsible for the link below\n\npurchase link = "https://shopee.co.id/Mainan-Anak-Edukatif-Alat-Musik-Tradisional-Seruling-Bambu-i.9543076.19450912158?sp_atk=987dc337-0a89-4ea8-a1b1-a4ce35f33900&xptdk=987dc337-0a89-4ea8-a1b1-a4ce35f33900"\n\n video link = "https://www.youtube.com/watch?v=cVumThGBdEg"',
  'jawabarat_tarawangsa':
      'Tarawangsa\n\nThe Sundanese tarawangsa is a wooden instrument played by simultaneously bowing and plucking. It consists of a stem and a bow. It has two strings, the closest string being plucked and bowed, and the other string being plucked. Made from dadap, jengkol, candlenut, and kenanga wood, the tarawangsa was traditionally played during harvest celebrations as an offering to the goddess of rice (Dewi Sri), led by traditional elders.\n\nThe tarawangsa, made from dadap, jengkol, candlenut, and kenanga wood, was traditionally played during harvest celebrations as an offering to the goddess of rice (Dewi Sri), led by traditional elders. When the music from the Sundanese musical instruments jentréng and tarawangsa is played. The dancers consisting of men and women will dance in an irregular style or without a certain pattern.\n\nBecause of this movement, some people think that the dancer has been entered by another spirit and is not aware of what he is doing.\n\n below is a link to buy and how to play the musical instrument \n*disclaimer admin is not responsible for the link below\n\npurchase link = "https://shopee.co.id/Kacapi-Jentreng-Tarawangsa-i.10971128.284559901?sp_atk=dd9177d9-6682-4dcb-a76c-bb272f08cfa2&xptdk=dd9177d9-6682-4dcb-a76c-bb272f08cfa2"\n\n video link = "https://www.tiktok.com/@egargarda/video/7335266141775924486"',
  'jawatengah_bonang':
      'Bonang\n\nThe bonang is a traditional Central Javanese percussion instrument made of brass, iron, or bronze. To play it, a special beater made of wood covered with rubber or cloth is required.\n\nBonang are divided into two types based on their size. The first is the larger bonang barung and the smaller bonang penerus.\n\nThe bonang barung has a mid-to-high octave tone and is usually used as an opening instrument in ensembles. This instrument can also lead other instruments when played using the pipilan percussion technique.\n\nFurthermore, the bonang barung can also form patterns and embellishments in songs when played using the imbal-imbalan percussion technique.\n\nMeanwhile, the bonang penerus has a high octave tone. When played with the pipilan percussion technique, the bonang panerus is twice as fast as the bonang barung.\n\nThen, if played with the imbal-imbalan percussion technique, the bonang penerus can play interwoven song patterns.\n\n below is the link to buy and how to play the musical instrument \n*disclaimer admin is not responsible for the link below\n\npurchase link = "https://shopee.co.id/Gamelan-Bonang-Besi-Pencu-Kuningan-i.109649775.1940168819?sp_atk=f0e9a585-e51d-4e97-819b-c64b7924fb55&xptdk=f0e9a585-e51d-4e97-819b-c64b7924fb55"\n\n video link = "https://www.youtube.com/watch?v=-oBi_7_YtJA"',
  'jawatengah_demung':
      'Demung\n\n Demung is a traditional musical instrument from Central Java that is part of the balungan family. In gamelan music performances, demung is divided into two types: the pelog-tuned demung and the slendro-tuned demung.\n\nUniquely, despite its large size, the demung actually has the lowest octave of pitch compared to other balungan instruments. This musical instrument is made of brass and is played by hitting it with a special beater.\n\n Below is a link to purchase and how to play the instrument \n*disclaimer admin is not responsible for the link below\n\npurchase link = "https://www.tokopedia.com/manunggal-jaya-art/demung-gamelan-kuningan-pelog-dplw7k?extParam=ivf%3Dfalse%26keyword%3Ddemung%26search_id%3D2025062403154034ED066DF378EF2D4LFM%26src%3Dsearch"\n\n video link = "https://www.youtube.com/watch?v=UVgMGoU2IIA"',
  'jawatengah_siter':
      'Siter\n\n Siter Similar to demung, Siter is also a musical instrument with pelog and slendro tones. However, the zither has 11 to 13 pairs of strings and is played by plucking.\n\nThe zither strings are played using the thumb, while the other fingers are responsible for holding the vibrations when the other strings are plucked. Typically, this traditional musical instrument is about 30 cm long and is placed in a box that acts as a resonator.\n\n Below is a link to purchase and how to play the instrument.\n*Disclaimer: The admin is not responsible for the link below.\n\npurchase link = "https://shopee.co.id/siter-ricikan-gamelan-siter-i.925765362.26533991958?sp_atk=6f6f6de7-1333-4326-a068-8ec714f48798&xptdk=6f6f6de7-1333-4326-a068-8ec714f48798"\n\nvideo link = "https://www.youtube.com/watch?v=SHJIPUfF07Q"',
  'jawatimur_kluncing':
      'Kluncing\n\n Kluncing is a typical musical instrumentEast Java, which looks similar to the Triangle musical instrument. This was influenced by the influx of European culture. The Kluncing is made of metal. Playing the Kluncing is very easy; simply strike it, and it will produce audible sounds. \n\n Below is a link to purchase and learn how to play the instrument. \n*disclaimer: admin is not responsible for the link below.\n\npurchase link = ""\n\nvideo link = ""',
  'jawatimur_saronen':
      'Saronen\n\n The Saronen is a traditional musical instrument from Madura, measuring up to 40 cm long and played by blowing. Like a flute, the player uses their fingers to control the notes. When played, the saronen can produce a loud and clear sound.\n\nThe difference between the Saronen and a typical flute is the number of holes. Saronen has seven holes, one hole is in a row at the back while the other six holes are in a row at the front.\n\n Below is a link to purchase and how to play the instrument \n*disclaimer admin is not responsible for the link below\n\npurchase link = "https://shopee.co.id/slompret-i.35857352.26362636299?sp_atk=04d20aa5-8fd6-4071-80b9-758a49a89644&xptdk=04d20aa5-8fd6-4071-80b9-758a49a89644"\n\n video link = "https://www.youtube.com/watch?v=MG3zTJul1OQ"',
  'yogjakarta_kendang':
      'Kendang/Gendang\n\n The drum is a popular traditional musical instrument from Yogyakarta. Besides Yogyakarta, this instrument is also known in several other regions, such as Central Java, West Java, and East Java. The drum is played without the aid of instruments, simply by striking it with the palms of the hands. This instrument typically plays the role of rhythm control. Yogyakarta residents also know the drum as a kendang. Small drums are called ketipung while larger ones are called kendang or ciblon.\n\n below is a link to buy and how to play the musical instrument \n*disclaimer admin is not responsible for the link below\n\npurchase link = "https://www.tokopedia.com/giripurwaseni/kendang-jaipong-1-set-rampak-kayu-mangga-1729579804834368125?extParam=ivf%3Dfalse%26keyword%3Dkendang%26search_id%3D2025062403373594F6D7E04A4D453C0IY5%26src%3Dsearch"\n\n video link = "https://www.youtube.com/watch?v=3F6FsJp1zXw"'
};
